#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6475010738                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                         # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Tutti                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Skip the printer. Digitize your sheet music with Tutti for iPad!

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Starduck Studio, LLC                                
your_link                                 : https://starduck.studio                    
your_city                                 : Baltimore                                
email_address                             : hello@starduck.studio
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : starduckstudio
github_username                           : 
youtube_username                          :
mastodon_link                             :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Import your Sheet Music PDFs
    description                           : Browse the files on your iPad and import your sheet music with multi-selection support.
    fontawesome_icon_name                 : download
    
  - title                                 : Navigate your Scores
    description                           : Swipe or scrub through your scores using intuitive gestures.
    fontawesome_icon_name                 : hand-pointer

  - title                                 : Tags
    description                           : Organize your sheet music into collections with Tags.
    fontawesome_icon_name                 : tag

  - title                                 : Setlists
    description                           : Build and manage setlists for your next concert or recital using the scores in your library.
    fontawesome_icon_name                 : list-ol
  
  - title                                 : Drawing on Music 
    description                           : Markup your scores with pencil and marker tools
    fontawesome_icon_name                 : pencil-alt

  - title                                 : Portrait and Landscape Support
    description                           : Read your scores in portrait or landscape orientations.
    fontawesome_icon_name                 : tablet-alt

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/tutti-website-header-image.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#0050A4"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
